[pr_reviewer]
enable_review_labels_effort = true
enable_auto_approval = true

[github_app]
pr_commands = [
    "/review",
    "/improve",
]

handle_push_trigger = true
push_commands = [
    "/review",
    "/improve",
]

[review_agent]
enabled = true
publish_output = true
